import os

SQLALCHEMY_BASE_PG_CONN_URI = "postgresql+pg8000://postgres:"
SQLALCHEMY_DB_HOST = os.environ["POSTGRES_HOST"]
SQLALCHEMY_DB = os.environ["POSTGRES_DB"]
SQLALCHEMY_DB_USER = os.environ["POSTGRES_USER"]
SQLALCHEMY_DB_PASSWORD = os.environ["POSTGRES_PASSWORD"]
SQLALCHEMY_DB_PORT = os.environ["POSTGRES_DB_PORT"]

#SQLALCHEMY_PG_CONN_URI = "postgresql+pg8000://postgres:testpass@localhost:5432/blog"
SQLALCHEMY_PG_CONN_URI = f"{SQLALCHEMY_BASE_PG_CONN_URI}:{SQLALCHEMY_DB_PASSWORD}@{SQLALCHEMY_DB_HOST}:{SQLALCHEMY_DB_PORT}/{SQLALCHEMY_DB}"
SQLALCHEMY_SQLITE_CONN_URI = "sqlite:///db/blog.db"
SQLALCHEMY_BASE_SQLITE_CONN_URI = "sqlite:///db/"
DB_TYPE = 1
DB_ECHO = False