# Generated by Django 4.2.1 on 2023-05-30 13:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsbaikal', '0002_remove_questionanswers_question_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=50), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='questionanswers',
            name='feedback',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
