# Generated by Django 4.2.1 on 2023-05-30 14:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsbaikal', '0003_alter_question_tags_alter_questionanswers_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=50), default=list, null=True, size=None),
        ),
    ]
