version: "3"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/local/postgresql/data/pgdata
    container_name: postgres-db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/local/postgresql/data/pgdata
    networks:
      - pythonapp

  web:
    build: .
    depends_on:
      - postgres
    container_name: python-app-web
    working_dir: /var/app
    environment:
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_TABLE_PREFIX: ${POSTGRES_TABLE_PREFIX}
        POSTGRES_DB_PERSIST: ${POSTGRES_DB_PERSIST}
        POSTGRES_DB_PORT: ${POSTGRES_DB_PORT}
        POSTGRES_DB_SOCKET: ${POSTGRES_DB_SOCKET}
        POSTGRES_DB_COLLATION: ${POSTGRES_DB_COLLATION}
        WWW_ROOT: ${WWW_ROOT}
    volumes:
      - ./:/var/app
    ports:
      - "8000:5000"
    networks:
      - pythonapp

volumes:
  db-data:

networks:
  pythonapp:
    driver: bridge