# Generated by Django 4.2.1 on 2023-05-29 07:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('question_text', models.CharField(max_length=200)),
                ('course_id', models.IntegerField(default=0)),
                ('course_module_id', models.IntegerField(default=0)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=50), size=None)),
                ('penalty', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField(default=0)),
                ('answer', models.CharField(max_length=500)),
                ('answer_format', models.IntegerField(default=0)),
                ('fraction', models.FloatField(default=1.0)),
                ('feedback', models.CharField(max_length=50)),
                ('feedback_format', models.IntegerField(default=0)),
            ],
        ),
    ]
