# Generated by Django 4.2.1 on 2023-05-29 14:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmsbaikal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswers',
            name='question_id',
        ),
        migrations.AddField(
            model_name='question',
            name='changed_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date changed'),
        ),
        migrations.AddField(
            model_name='question',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='questionanswers',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lmsbaikal.question'),
        ),
    ]
