# Generated by Django 4.2.1 on 2023-05-30 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsbaikal', '0004_alter_question_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='changed_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 30, 19, 48, 45, 417669, tzinfo=datetime.timezone.utc), verbose_name='date changed'),
        ),
        migrations.AlterField(
            model_name='question',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 30, 19, 48, 45, 417650, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
