# Generated by Django 4.2.1 on 2023-05-30 20:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lmsbaikal', '0008_alter_question_changed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='changed_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date changed'),
        ),
        migrations.AlterField(
            model_name='question',
            name='publication_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
